env:
  global:
    - OMPI_MCA_rmaps_base_oversubscribe=yes
    - MINICONDA_VERSION="latest"
    - MINICONDA_PYTHON_MAJOR=2
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  allow_failures:
  - name: "linux openmpi"
  include:
  - name: "linux MPICH Py3"
    language: python
    python:
    - '3.7'
    compiler: gcc
    before_install:
    - pip install numpy scipy matplotlib nose docutils mpi4py h5py
    install:
    - ./configure
    - make framework
    addons:
      apt:
        packages:
        - build-essential
        - python3-dev
        - gfortran
        - libgsl0-dev
        - cmake
        - libfftw3-3
        - libfftw3-dev
        - libmpfr4
        - libmpfr-dev
        - libhdf5-serial-dev
        - hdf5-tools
        - libmpich-dev
        - mpich  
  - name: "linux MPICH Py2"
    language: python
    python:
    - '2.7'
    compiler: gcc
    before_install:
    - pip install numpy scipy matplotlib nose docutils mpi4py h5py
    install:
    - ./configure
    - make framework
    addons:
      apt:
        packages:
        - build-essential
        - python-dev
        - gfortran
        - libgsl0-dev
        - cmake
        - libfftw3-3
        - libfftw3-dev
        - libmpfr4
        - libmpfr-dev
        - libhdf5-serial-dev
        - hdf5-tools
        - libmpich-dev
        - mpich  
  - name: "macOS 10.14 openmpi py3 homebrew"
    osx_image: xcode10.3
    language: python
    python:
    - '3.7'
    compiler: gcc
    before_install:
    - pip install numpy scipy matplotlib nose docutils mpi4py h5py
    install:
    - ./configure
    - make framework
    addons:
      homebrew:
        packages:
        - gcc
        - fftw
        - open-mpi
        - cmake
        - hdf5

virtualenv:
  system_site_packages: false

script:
- export PYTHONPATH=${PWD}/src:${PWD}
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    mpiexec nosetests amuse.test.suite.compile_tests.test_python_implementation:TestInterface.test10 -sv
    mpiexec nosetests test/reports/test_speed.py -sv
    mpiexec nosetests -e "test_plot" test/core_tests
    mpiexec nosetests -e "test_cython_implementation" test/compile_tests -sv
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    nosetests test/reports/test_speed.py -sv
    nosetests -e "test_plot" test/core_tests
    nosetests test/compile_tests/test_c_implementation.py -sv
    #nosetests test/compile_tests/test_c_sockets_implementation.py -sv
    nosetests test/compile_tests/test_fortran_implementation.py -sv
    #nosetests test/compile_tests/test_fortran_sockets_implementation.py -sv
    nosetests test/compile_tests/test_python_implementation.py -sv
  fi
