language: python
python:
- '2.7'

os:
  - linux

dist: trusty

sudo: enabled

compiler:
  - gcc

install:
- pip install numpy scipy matplotlib nose docutils mpi4py h5py
- ./configure
- python setup.py install --user

virtualenv:
  system_site_packages: false

before_install:
- sudo apt-get install build-essential
- sudo apt-get install gfortran 
- sudo apt-get install python-dev
- sudo apt-get install libgsl0-dev
- sudo apt-get install cmake
- sudo apt-get install libfftw3-3
- sudo apt-get install libfftw3-dev
- sudo apt-get install libmpfr4
- sudo apt-get install libmpfr-dev
- sudo apt-get install libhdf5-serial-dev
- sudo apt-get install hdf5-tools
- sudo apt-get install libopenmpi-dev
- sudo apt-get install openmpi-bin

script:
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/core_tests
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_bhtree.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_bridge.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_bse.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_encounters.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_fi.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_gravity_codes.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_hermite.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_hop.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_lab.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_seba.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_sse.py
- nosetests ~/.local/lib/python2.7/site-packages/amuse/test/suite/ticket_tests/
