env:
  global:
    - OMPI_MCA_rmaps_base_oversubscribe=yes
    - MINICONDA_VERSION="latest"
    - MINICONDA_PYTHON_MAJOR=2
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  allow_failures:
  - name: "linux openmpi"
  include:
  - name: "linux MPICH Py2"
    os: linux
    language: python
    python:
    - '2.7'
    compiler: gcc
    before_install:
    - pip install numpy scipy matplotlib nose docutils mpi4py h5py
    install:
    - cd packages/amuse-framework && python setup.py sdist && cd ../../
    - pip install packages/amuse-framework/dist/*.tar.gz
    addons:
      apt:
        packages:
        - build-essential
        - python-dev
        - gfortran
        - libgsl0-dev
        - cmake
        - libfftw3-3
        - libfftw3-dev
        - libmpfr4
        - libmpfr-dev
        - libhdf5-serial-dev
        - hdf5-tools
        - libmpich-dev
        - mpich  
  - name: "macOS 10.14 openmpi py2 homebrew"
    os: osx
    osx_image: xcode10.3
    env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-9 && CXX=g++-9"
    addons:
      homebrew:
        packages:
        - gcc
        - fftw
        - open-mpi
        - cmake
        - hdf5
        - python@2
    language: python
    python:
    - '2.7'
    compiler: gcc
    before_install:
    - eval "${MATRIX_EVAL}"
    - pip install numpy scipy matplotlib nose docutils mpi4py h5py
    install:
    - cd packages/amuse-framework && python setup.py sdist && cd ../../
    - pip install packages/amuse-framework/dist/*.tar.gz

virtualenv:
  system_site_packages: false

script:
- export PYTHONPATH=${PWD}/src:${PWD}
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    mpiexec pytest amuse.test.suite.compile_tests.test_python_implementation:TestInterface.test10 -v
    mpiexec pytest test/reports/test_speed.py -v
    mpiexec pytest -k "not test_plot" test/core_tests -v
    mpiexec pytest -k "not test_cython_implementation" test/compile_tests -v
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pytest test/reports/test_speed.py -v
    pytest -k "not test_plot" test/core_tests
    pytest test/compile_tests/test_c_implementation.py -v
    #pytest test/compile_tests/test_c_sockets_implementation.py -v
    pytest test/compile_tests/test_fortran_implementation.py -v
    #pytest test/compile_tests/test_fortran_sockets_implementation.py -v
    pytest test/compile_tests/test_python_implementation.py -v
  fi
