language: python
python:
- '2.7'

os:
  - linux

dist: trusty

sudo: enabled

compiler:
  - gcc

install:
- pip install numpy scipy matplotlib nose docutils mpi4py h5py
- ./configure
- make framework

virtualenv:
  system_site_packages: false

before_install:
- sudo apt-get install build-essential
- sudo apt-get install gfortran 
- sudo apt-get install python-dev
- sudo apt-get install libgsl0-dev
- sudo apt-get install cmake
- sudo apt-get install libfftw3-3
- sudo apt-get install libfftw3-dev
- sudo apt-get install libmpfr4
- sudo apt-get install libmpfr-dev
- sudo apt-get install libhdf5-serial-dev
- sudo apt-get install hdf5-tools
- sudo apt-get install libopenmpi-dev
- sudo apt-get install openmpi-bin

script:
- export PYTHONPATH=${PWD}/src
- nosetests test/core_tests/test_amusetest.py
- nosetests test/core_tests/test_attribute_error.py
- nosetests test/core_tests/test_attribute_storage.py
- nosetests test/core_tests/test_binaryio.py
- nosetests test/core_tests/test_bridge.py
- nosetests test/core_tests/test_console.py
- nosetests test/core_tests/test_constants.py
- nosetests test/core_tests/test_generate_fortran.py
- nosetests test/core_tests/test_generic_units.py
- nosetests test/core_tests/test_grid_attributes.py
#- nosetests test/core_tests/test_grid_implementation.py
- nosetests test/core_tests/test_grids.py
- nosetests test/core_tests/test_incode_particle_sets.py
- nosetests test/core_tests/test_incode_storage.py
- nosetests test/core_tests/test_indexing.py
- nosetests test/core_tests/test_inmemorystorage.py
- nosetests test/core_tests/test_interface.py
- nosetests test/core_tests/test_io.py
- nosetests test/core_tests/test_links.py
- nosetests test/core_tests/test_literature.py
- nosetests test/core_tests/test_nbody_units.py
- nosetests test/core_tests/test_nemo.py
- nosetests test/core_tests/test_options.py
- nosetests test/core_tests/test_optparse.py
- nosetests test/core_tests/test_parameters.py
- nosetests test/core_tests/test_particle_attributes.py
- nosetests test/core_tests/test_particles.py
- nosetests test/core_tests/test_particles_properties.py
- nosetests test/core_tests/test_phigrape.py
- nosetests test/core_tests/test_pickle.py
- nosetests test/core_tests/test_plot.py
- nosetests test/core_tests/test_quantities.py
- nosetests test/core_tests/test_rotation.py
- nosetests test/core_tests/test_scaling_converter.py
- nosetests test/core_tests/test_staggeredgrid.py
- nosetests test/core_tests/test_starlab.py
- nosetests test/core_tests/test_stopping_conditions.py
- nosetests test/core_tests/test_store.py
- nosetests test/core_tests/test_textio.py
- nosetests test/core_tests/test_trees.py
- nosetests test/core_tests/test_unit_conversion.py
- nosetests test/core_tests/test_vtkio.py
