language: python
python:
- '2.7'

os:
  - linux

dist: trusty

sudo: false

compiler:
  - gcc

install:
- ./configure
  python setup.py install

virtualenv:
  system_site_packages: false

before_install:
- pip install numpy scipy matplotlib nose docutils mpi4py h5py

script:
- nosetests
