theme: just-the-docs
title: Astrophysical simulations with AMUSE
description: AMUSE provides a Python interface to many astrophysical simulation codes
logo: images/amuse-logo.png
show_downloads: true
