theme: jekyll-theme-minimal
title: AMUSE - Astrophysical simulations
description: AMUSE provides a Python interface to many astrophysical simulation codes
logo: images/amuse-logo.png
show_downloads: true
