name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.7', '3.10']
    env:
      OS: ${{ matrix.os }}
      PYTHONVER: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install gfortran libopenblas-dev libhdf5-openmpi-dev libgsl0-dev cmake libfftw3-3 libfftw3-dev libmpfr6 libmpfr-dev
        pip install numpy scipy matplotlib docutils mpi4py pytest pytest-timeout pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install amuse
      run: |
        export SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
        pip install -e . --config-settings editable_mode=compat
    - name: build AMUSE framework
      run: |
        make framework
    - name: Generate coverage report
      run: |
        pytest src/amuse/test/suite/core_tests --cov=./src/amuse/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHONVER
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
