name: Pylint

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        py-version:
          #- 3.5
          #- 3.6
          - 3.7
          #- 3.8
          #- 3.9
        py-arch:
          - x64
        mpi:
          #- mpich
          - openmpi
        os:
          - ubuntu-latest
          #- ubuntu-18.04
          #- ubuntu-20.04
          #- macos-10.15
          #- macos-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - uses: jitterbit/get-changed-files@v1
      id: files
      with:
        format: csv
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}
        architecture: ${{ matrix.py-arch }}
    - name: Install dependencies
      run: python -m pip install pylint
    - name: Analysing the code with pylint
      run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          pylint ${added_modified_file};
        done
