name: Test AMUSE mosse

on:
  push:
    paths:
      - .github/workflows/test-mosse.yml
      - 'src/amuse_mosse/**'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-mosse.yml
      - 'src/amuse_mosse/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict

    - name: Show conda info
      run: |
        conda info
        conda list

    - name: Install dependencies
      run: |
        conda install c-compiler cxx-compiler fortran-compiler 'gfortran<14' python pkgconfig coreutils patch curl tar unzip gzip bzip2 xz perl bison make cmake 'openmpi<5' gsl fftw gmp mpfr hdf5 netcdf4 libopenblas liblapack zlib pip wheel 'docutils>=0.6' 'mpi4py>=1.1.0' 'numpy>=1.2.2' 'h5py>=1.1.0' pytest

    - name: Configure OpenMPI
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        mkdir -p "$HOME/.openmpi"
        echo "btl_tcp_if_include = lo" >>"$HOME/.openmpi/mca-params.conf"
        echo "rmaps_base_oversubscribe = true" >>"$HOME/.openmpi/mca-params.conf"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Build mosse
      run: |
        ./setup install amuse-mosse

    - name: Ensure we test only the installed package
      run: |
        ./setup distclean

    - name: Test mosse
      run: |
        ./setup test amuse-mosse

    - name: Archive build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os }}
        path: ${{ github.workspace }}/support/logs/
        if-no-files-found: warn
